# Exercise the real executable without proprietary assets.
file(MAKE_DIRECTORY "${SCRATCH}")
if (CASE STREQUAL "missing-value")
    set(arguments -datadir)
    set(expected "requires a directory argument")
elseif (CASE STREQUAL "invalid-directory")
    set(arguments -datadir "${SCRATCH}/does-not-exist")
    set(expected "cannot access data directory")
elseif (CASE STREQUAL "unknown-option")
    set(arguments -not-a-real-option)
    set(expected "invalid command line")
elseif (CASE STREQUAL "missing-data")
    set(arguments -datadir "${SCRATCH}")
    set(expected "required game file")
else ()
    message(FATAL_ERROR "Unknown startup test case: ${CASE}")
endif ()
execute_process(COMMAND "${CLIENT}" ${arguments}
    WORKING_DIRECTORY "${SCRATCH}"
    TIMEOUT 20 RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if (NOT result STREQUAL "1")
    message(FATAL_ERROR "Expected exit 1, got ${result}: ${output}${error}")
endif ()
string(FIND "${output}${error}" "${expected}" found)
if (found EQUAL -1)
    message(FATAL_ERROR "Missing diagnostic '${expected}': ${output}${error}")
endif ()
if (CASE STREQUAL "missing-data")
    set(log "${SCRATCH}/Logs/Northrend.log")
    if (NOT EXISTS "${log}")
        message(FATAL_ERROR "Startup log was not created: ${log}")
    endif ()
    file(READ "${log}" contents)
    foreach (stage "Northrend 3.3.5a" "architecture=" "Data directory:" "Renderer:" "Fatal: required game file")
        string(FIND "${contents}" "${stage}" found)
        if (found EQUAL -1)
            message(FATAL_ERROR "Missing log diagnostic: ${stage}")
        endif ()
    endforeach ()
endif ()
