name: Push

on:
  push:
    branches:
      - northrend
      - development
      - master
  pull_request:
    branches: [northrend]

concurrency:
  group: northrend-build-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.config.name }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        config:
          - name: Ubuntu Latest (GCC)
            os: ubuntu-latest
            cc: gcc
            cxx: g++

          - name: macOS Latest (Clang)
            os: macos-latest
            cc: clang
            cxx: clang++

          - name: Windows Latest (MSVC)
            os: windows-latest
            cc: cl
            cxx: cl

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: What OS?
        shell: bash
        run: |
          echo "$RUNNER_OS / $RUNNER_ARCH"
          cmake --version
          uname -m

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libopengl-dev libglx-dev libxext-dev libglvnd-dev

      - name: Prepare
        run: mkdir build

      - name: Configure
        run: cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel 3

      - name: Test
        run: ctest --test-dir build -C ${{ matrix.build_type }} --output-on-failure
